version: '3.8'

services:
  tavily-search-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: tavily-search-mcp-server:latest
    container_name: tavily-search-mcp-server
    ports:
      - "3001:3001"
    environment:
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - TRANSPORT=${TRANSPORT:-stdio} # Default to stdio if not set
    volumes:
      - ./src:/app/src
    restart: unless-stopped